export const ErrorType = {
    AUTHENTICATION: "authentication_error",
    AUTHORIZATION: "authorization_error",
    VALIDATION: "validation_error",
    NOT_FOUND: "not_found_error",
    CONFLICT: "conflict_error",
    SERVER: "server_error",
} as const;

export const ErrorCode = {
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
    AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
    AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

    FORBIDDEN: "FORBIDDEN",

    USER_NOT_FOUND: "USER_NOT_FOUND",

    GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
    GROUP_ALREADY_EXISTS: "GROUP_ALREADY_EXISTS",

    TIMETABLE_NOT_FOUND: "TIMETABLE_NOT_FOUND",
    TIMETABLE_ALREADY_EXISTS: "TIMETABLE_ALREADY_EXISTS",

    ENTRY_NOT_FOUND: "ENTRY_NOT_FOUND",
    ENTRY_CONFLICT: "ENTRY_CONFLICT",

    TASK_NOT_FOUND: "TASK_NOT_FOUND",

    INVITE_INVALID: "INVITE_INVALID",
    INVITE_EXPIRED: "INVITE_EXPIRED",
    ALREADY_A_MEMBER: "ALREADY_A_MEMBER",

    VALIDATION_ERROR: "VALIDATION_ERROR",

    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;